### ISSUE TITLE
Poor Drastic r2.5.2.2 performance on CrossMix-OS v1.2.1

### ISSUE THREAD

**Issue by Soupnazi1981** [cizia64/CrossMix-OS#106]
Love your firmware by the way! :)

On a fresh install of CrossMix-OS v1.2.1, Nintendo DS  Drastic r2.5.2.2 has very poor performance. When loading any game, even the title screen is running at low fps and sound is constantly stuttering. Once gameplay starts, it's even worse and games are a slideshow. I've tried turning autoframe skip on, preload roms, as well as adjusting the video options but no luck. Eg. Mario Kart, Castlevania (all of them), Contra 4, as well as any other game I've tried. I don't remember stock OS 1.0.4 having unplayable DS performance?

**Comment by gabrielpsp** [comment]
I'm not sure myself but I feel kinda downgrade too with PPSSPP

**Comment by cizia64** [comment]
Yes it has been fixed. Only those who have downloaded the v1.2.1 in the first 7 hours are concerned by this problem.
This is due to also configuration. 

**To fix it just run OTA update from apps.**

For those who don't want to enable wifi on their TSP,  here the manual way : copy [this asound.conf file](https://github.com/cizia64/CrossMix-OS/blob/main/System/usr/trimui/etc/asound.conf) in `/etc` on the internal storage (ROOT) , reboot and try again NDS

**Comment by Soupnazi1981** [comment]
> Yes it has been fixed. Only those who have downloaded the v1.2.1 in the first 7 hours are concerned by this problem. This is due to alsa configuration.
> 
> **To fix it just run OTA update from apps.**
> 
> For those who don't want to enable wifi on their TSP, here the manual way : copy [this asound.conf file](https://github.com/cizia64/CrossMix-OS/blob/main/System/usr/trimui/etc/asound.conf) in `/etc` on the internal storage (ROOT) , reboot and try again NDS

You are awesome! Thanks for responding so quickly and also implementing the fix via the cool OTA update feature. I can confirm that NDS performance is now back to normal and no more stuttering at all. Keep up the great work!

**Comment by nicmasc** [comment]
Hi @cizia64, thanks for your great work. I'm on 1.2.1 and even though I downloaded crossmix after the first 7 hours, unfortunately I'm still experiencing audio problems on Drastic, can you give me some further suggestions?

**Comment by cizia64** [comment]
The asound.conf fix on v1.2.1, enabling "Threaded 3D" and disabling "High resolution 3D" are good ways to improve performances. I close.
